#!/usr/bin/env python
import pprint
show_ip_int_brief = '''
Interface            IP-Address      OK?     Method      Status     Protocol
FastEthernet0   unassigned      YES     unset          up          up
FastEthernet1   unassigned      YES     unset          up          up
FastEthernet2   unassigned      YES     unset          down      down
FastEthernet3   unassigned      YES     unset          up          up
FastEthernet4    6.9.4.10          YES     NVRAM       up          up
NVI0                  6.9.4.10          YES     unset           up          up
Tunnel1            16.25.253.2     YES     NVRAM       up          down
Tunnel2            16.25.253.6     YES     NVRAM       up          down
Vlan1                unassigned      YES    NVRAM       down      down
Vlan10              10.220.88.1     YES     NVRAM       up          up
Vlan20              192.168.0.1     YES     NVRAM       down      down
Vlan100            10.220.84.1     YES     NVRAM       up          up
'''
show_split = show_ip_int_brief.split("\n")
listala = []

for entry in show_split:
    if 'Interface' in entry:
        continue
    line_split = entry.split()
    if len(line_split) == 6:
        if_name, ip_addr, discard1, discard2, line_status, line_proto = line_split
        if (line_status == 'up') and (line_proto == 'up'):
            listala.append((if_name, ip_addr, line_status, line_proto))

pprint.pprint(listala)
print "\n"

